# Generated by Django 4.1.7 on 2023-02-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateUser',
            new_name='Users',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='userName',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
