# Generated by Django 4.1.7 on 2023-02-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0002_rename_createuser_users_rename_name_users_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='subscriptionId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='businessName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='contactNumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='userName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
