# Generated by Django 4.1.7 on 2023-02-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0003_users_subscriptionid_alter_users_businessname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('subscriptionId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=100, null=True)),
                ('planType', models.CharField(max_length=100, null=True)),
                ('paymentMethod', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
