# Generated by Django 4.1.7 on 2023-03-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('incomeCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('incomeCategory', models.CharField(max_length=100, null=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Income',
            },
        ),
    ]
