# Generated by Django 4.1.7 on 2023-03-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('incomeCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('incomeCategory', models.CharField(max_length=100, null=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Expenses',
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('wordId', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100, null=True)),
                ('categoryID', models.CharField(max_length=100, null=True)),
                ('sub_category', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'Keywords',
            },
        ),
    ]
