# Generated by Django 4.1.7 on 2023-03-07 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_expense_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='incomeCategory',
            new_name='expenseCategory',
        ),
    ]
