# Generated by Django 4.1.7 on 2023-03-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_rename_incomecategory_expense_expensecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='incomeCategoryId',
            new_name='expenseCategoryId',
        ),
    ]
